apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  WRITE_USERNAME: {{ .Values.db.writeUsername }}
  WRITE_PASSWORD: {{ .Values.db.writePassword }}
  READ_USERNAME: {{ .Values.db.readUsername }}
  READ_PASSWORD: {{ .Values.db.readPassword }}
