apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
#  labels:
#    app: go-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DB_WRITE_USERNAME
{{/*              value: postgres*/}}
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: WRITE_USERNAME
            - name: DB_WRITE_PASSWORD
{{/*              value: postgres*/}}
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: WRITE_PASSWORD
            - name: DB_READ_USERNAME
{{/*              value: postgres*/}}
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: READ_USERNAME
            - name: DB_READ_PASSWORD
{{/*              value: postgres*/}}
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: READ_PASSWORD
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: go-app-configmap
                  key: APP_PORT
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            requests:
              memory: {{ .Values.app.resources.requests.memory }}
              cpu: "{{ .Values.app.resources.requests.cpu }}"
            limits:
              memory: {{ .Values.app.resources.limits.memory }}
              cpu: "{{ .Values.app.resources.limits.cpu }}"
      volumes:
        - name: config-volume
          configMap:
            name: go-app-configmap
