apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
#  labels:
#    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: h0si/cc-project-k8s
#          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1323
          env:
            - name: DB_WRITE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: WRITE_USERNAME
            - name: DB_WRITE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: WRITE_PASSWORD
            - name: DB_READ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: READ_USERNAME
            - name: DB_READ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: READ_PASSWORD
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: go-app-configmap
                  key: APP_PORT
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            requests:
              memory: 128Mi
              cpu: "0.5"
            limits:
              memory: 256Mi
              cpu: "1"
      volumes:
        - name: config-volume
          configMap:
            name: go-app-configmap
