apiVersion: v1
kind: Service
metadata:
  name: db-read-svc
#  labels:
#    app: postgres
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}