db:
  image: postgres
  tag: 15.3-alpine3.18
  name: postgres
  writeUsername: cG9zdGdyZXM=
  writePassword: cG9zdGdyZXM=
  readUsername: cG9zdGdyZXM=
  readPassword: cG9zdGdyZXM=
  port: 5432
  resources:
    requests:
      memory: 256Mi
      cpu: 0.5
    limits:
      memory: 512Mi
      cpu: 1
  storage: 1Gi
  replicas: 2

app:
  image: h0si/cc-project-k8s
  tag: latest
  name: go-app
  port: 1323
  checkInterval: 1
  replicas: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 0.5
    limits:
      memory: 512Mi
      cpu: 1

postgresql:
  auth:
    replicationUsername: postgres
    replicationPassword: postgres
    username: postgres
    password: postgres
    postgresPassword: postgres
  architecture: replication
  readReplicas:
    replicaCount: 2

hpa:
  minPods: 1
  maxPods: 10